version: '3.8'

# REPO_PREFIX is used in CI to deploy to other docker registries than dockerhub.

services:

  factory:
    image: ${REPO_PREFIX-}mjhenkes/factory
    build:
      dockerfile: factory.Dockerfile
      target: factory
      context: .
      args:
        BASE_IMAGE: ${BASE_IMAGE}
        DEFAULT_NODE_VERSION: ${NODE_VERSION}
      tags:
       - ${REPO_PREFIX-}mjhenkes/factory:${FACTORY_VERSION}
    command: node -v

  included:
    image: ${REPO_PREFIX-}mjhenkes/included
    build:
      target: included_image
      context: .
      args:
        FACTORY_VERSION: ${FACTORY_VERSION}
        CHROME_VERSION: ${CHROME_VERSION}
        CYPRESS_VERSION: ${CYPRESS_VERSION}
        EDGE_VERSION: ${EDGE_VERSION}
        FIREFOX_VERSION: ${FIREFOX_VERSION}
        YARN_VERSION: ${YARN_VERSION}
        # WEBKIT_VERSION: ${WEBKIT_VERSION}
      tags:
       - ${REPO_PREFIX-}mjhenkes/included:${INCLUDED_IMAGE_TAG}
    command: node -v

  browsers:
    image: ${REPO_PREFIX-}mjhenkes/browsers
    build:
      target: default_image
      context: .
      args:
        FACTORY_VERSION: ${FACTORY_VERSION}
        YARN_VERSION: ${YARN_VERSION}
        CHROME_VERSION: ${CHROME_VERSION}
        FIREFOX_VERSION: ${FIREFOX_VERSION}
        EDGE_VERSION: ${EDGE_VERSION}
      tags:
       - ${REPO_PREFIX-}mjhenkes/browsers:${BROWSERS_IMAGE_TAG}
    command: node -v

  base:
    image: ${REPO_PREFIX-}mjhenkes/base
    build:
      target: default_image
      context: .
      args:
        FACTORY_VERSION: ${FACTORY_VERSION}
        YARN_VERSION: ${YARN_VERSION}
      tags:
       - ${REPO_PREFIX-}mjhenkes/base:${BASE_IMAGE_TAG}
    command: node -v

  ## Unused images that we could release in the future if we choose.
  chrome:
    image: "${REPO_PREFIX-}mjhenkes/chrome"
    build:
      target: default_image
      context: .
      args:
        FACTORY_VERSION: ${FACTORY_VERSION}
        CHROME_VERSION: ${CHROME_VERSION}
      tags:
       - ${REPO_PREFIX-}mjhenkes/chrome:${CHROME_VERSION}
    command: google-chrome --version

  edge:
    image: ${REPO_PREFIX-}mjhenkes/edge
    build:
      target: default_image
      context: .
      args:
        FACTORY_VERSION: ${FACTORY_VERSION}
        EDGE_VERSION: ${EDGE_VERSION}
      tags:
       - ${REPO_PREFIX-}mjhenkes/edge:${EDGE_VERSION}
    command: edge --version

  firefox:
    image: ${REPO_PREFIX-}mjhenkes/firefox
    build:
      target: default_image
      context: .
      args:
        FACTORY_VERSION: ${FACTORY_VERSION}
        FIREFOX_VERSION: ${FIREFOX_VERSION}
      tags:
       - ${REPO_PREFIX-}mjhenkes/firefox:${FIREFOX_VERSION}
    command: firefox --version

  # webkit:
  #   image: ${REPO_PREFIX-}mjhenkes/webkit
  #   build:
  #     target: default_image
  #     context: .
  #     args:
  #       FACTORY_VERSION: ${FACTORY_VERSION}
  #       WEBKIT_VERSION: ${WEBKIT_VERSION}
  #     tags:
  #     - ${REPO_PREFIX-}mjhenkes/webkit:${WEBKIT_VERSION}
  #   command: webkit --version

  cypress:
    image: ${REPO_PREFIX-}mjhenkes/cypress
    build:
      target: default_image
      context: .
      args:
        FACTORY_VERSION: ${FACTORY_VERSION}
        CYPRESS_VERSION: ${CYPRESS_VERSION}
      tags:
       - ${REPO_PREFIX-}mjhenkes/cypress:${CYPRESS_VERSION}
    command: cypress verify

  cypress-chrome:
    image: ${REPO_PREFIX-}mjhenkes/cypress-chrome
    build:
      target: default_image
      context: .
      args:
        FACTORY_VERSION: ${FACTORY_VERSION}
        CYPRESS_VERSION: ${CYPRESS_VERSION}
        CHROME_VERSION: ${CHROME_VERSION}
      tags:
       - ${REPO_PREFIX-}mjhenkes/cypress-chrome:cypress-${CYPRESS_VERSION}-chrome-${CHROME_VERSION}
    command: node -v

  cypress-edge:
    image: ${REPO_PREFIX-}mjhenkes/cypress-edge
    build:
      target: default_image
      context: .
      args:
        FACTORY_VERSION: ${FACTORY_VERSION}
        CYPRESS_VERSION: ${CYPRESS_VERSION}
        EDGE_VERSION: ${EDGE_VERSION}
      tags:
       - ${REPO_PREFIX-}mjhenkes/cypress-edge:cypress-${CYPRESS_VERSION}-edge-${EDGE_VERSION}
    command: node -v

  cypress-firefox:
    image: ${REPO_PREFIX-}mjhenkes/cypress-firefox
    build:
      target: default_image
      context: .
      args:
        FACTORY_VERSION: ${FACTORY_VERSION}
        CYPRESS_VERSION: ${CYPRESS_VERSION}
        FIREFOX_VERSION: ${FIREFOX_VERSION}
      tags:
       - ${REPO_PREFIX-}mjhenkes/cypress-firefox:cypress-${CYPRESS_VERSION}-firefox-${FIREFOX_VERSION}
    command: node -v

  ## Test image
  test-node-override:
    build:
      target: default_image
      context: .
      args:
        FACTORY_VERSION: ${FACTORY_VERSION}
        NODE_VERSION: 16.17.0
    command: node -v
