# WARNING: this file was autogenerated by generate-included-image.js
# using
#   npm run add:included -- 12.2.0 cypress/browsers:https://github.com/cypress-io/cypress-docker-images/tree/master/browsers
set e+x

LOCAL_NAME=cypress/included:12.2.0-https
echo "Building $LOCAL_NAME"
docker build -t $LOCAL_NAME .
