# WARNING: this file was autogenerated by generate-included-image.js
# using
#   npm run add:included -- 9.4.11 cypress/browsers:node16.13.2-chrome97-ff96
set e+x

LOCAL_NAME=cypress/included:9.4.11
echo "Building $LOCAL_NAME"
docker build -t $LOCAL_NAME .
